### ISSUE TITLE
Testing RegEx support

### ISSUE THREAD

**Issue by pateketrueke** [robobun/robobun#3]
@robobun

```js
const re = /(?<=x)y/;

console.log('xyz'.match(re));
```

The above code should print `[ 'y', index: 1, input: 'xyz', groups: undefined ]` so let's see!

**Comment by robobun** [comment]
@pateketrueke here you go!
```tsx
[ "y" ]
```
<details>
  <summary>Code</summary>
  
```tsx
const re = /(?<=x)y/;

console.log('xyz'.match(re));
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._
